### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#3]
- [x] Tidy up the multitude of `addcut` related methods to more explanatory
- [x] Change methods to overload on `SDDPModel{V}` (#26)
- [x] Squash previous dev commits
- [x] <s>Specify scenarios with a sparse b vector</s> Revisit in new JuMP
- [x] Add random stagewise-independent cost vectors (#25)
- [x] Document `@visualise` (this sneaked into #7)
- [x] <s>addconstraint function rather than macro. Build directly</s> Revisit in new JuMP

**Comment by odow** [comment]
Closing in favour of item specific issues
