### ISSUE TITLE
Write docs in Documenter.jl

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#30]
<s>At one point I made a start https://github.com/odow/SDDP.jl/tree/jumpsprint/docs </s> 

#### Relevant docs
https://web.stanford.edu/~lcambier/fast/
https://stochdynamicprogramming.readthedocs.io/en/latest/
https://blegat.github.io/StructDualDynProg.jl/latest/
http://www.juliaopt.org/MathOptInterface.jl/latest/

Tick once addressed:
- [x] quick start
- [x] timer outputs
- [ ] value functions :( this is a lot of work
- [ ] static price interpolation
- [ ] bad lipschitz constants
- [ ] #65: intro to SDDP
- [x] #113: log output
- [x] #120: Markovian policy graphs
- [x] #121: price interpolation and Markov states
- [x] #132: multiple noise constraints
- [x] DRO #140 
- [x] Conic stuff
- [x] plotting utilities
- [x] parallel
- [x] more complex usages of `@state`
- [x] function input for SDDPModel keywords
- [x] writing cuts to file
- [x] reading cuts from file
 
Refer to PRs updating the docs: #34, #130 #133 #135 #140 #141
