### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#32]
Big things that aren't really tested (from [CodeCov](https://codecov.io/gh/odow/SDDP.jl)):
- [x] time limit termination (covered by #41)
- [ ] <s>user interruption termination</s> (not sure if possible?)
- [x] <s>asyncronous</s> (problems with coverage on remote workers) (improved by #43, #47)
- [x] visualiser (covered by #42, #46)
- [x] saving the model (covered by #41)

**Comment by odow** [comment]
Closing as coverge is now >95%. Will re-open a new issue in the future if it drops.
