### ISSUE TITLE
Add more problem descriptors

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#430]
We should add more problem descriptors to the print out. 
 - [ ] Integer yes/no #430
 - [ ] Solver name
 - [ ] Maximum size of subproblems? #430
 - [ ] Existing policy yes/no #430
 - [ ] Risk measure #430

Afterwards:
 - [ ] Total run-time #430
 - [ ] Total number of LPs solved #430
 - [ ] Total number of cuts added 
 - [ ] Simulation confidence interval from forward passes #430

**Comment by odow** [comment]
Closed by #438
